name: Build C++/CLI Server Manager

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet Packages
      run: nuget restore TeamFortress2ServerManager.sln

    - name: Build Solution in Release
      run: msbuild TeamFortress2ServerManager.sln /p:Configuration=Release /p:Platform=x64
