name: Build C++/CLI Server Manager

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build Project in Release
      run: msbuild TeamFortress2ServerManager/TeamFortress2ServerManager/TeamFortress2ServerManager.vcxproj /p:Configuration=Release /p:Platform=x64
